// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtup6EQ0k0x_icIfTMjngrjuW6jTjoLis',
    appId: '1:389758429719:web:08bc9fdbd9d3ced5014a52',
    messagingSenderId: '389758429719',
    projectId: 'facevit-tcc',
    authDomain: 'facevit-tcc.firebaseapp.com',
    storageBucket: 'facevit-tcc.appspot.com',
    measurementId: 'G-XG531EKZR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvJwyTS_TfLLp7dlakj_QVgawJ4GOYKs',
    appId: '1:389758429719:android:0f0cf3ad2f381ae9014a52',
    messagingSenderId: '389758429719',
    projectId: 'facevit-tcc',
    storageBucket: 'facevit-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkoZNUUxH22XU5-22_M3JsqckPqingUWI',
    appId: '1:389758429719:ios:00922485149b84a3014a52',
    messagingSenderId: '389758429719',
    projectId: 'facevit-tcc',
    storageBucket: 'facevit-tcc.appspot.com',
    iosBundleId: 'com.example.faceVit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkoZNUUxH22XU5-22_M3JsqckPqingUWI',
    appId: '1:389758429719:ios:cb0ed32040035045014a52',
    messagingSenderId: '389758429719',
    projectId: 'facevit-tcc',
    storageBucket: 'facevit-tcc.appspot.com',
    iosBundleId: 'com.example.faceVit.RunnerTests',
  );
}
